# Generated by Django 4.2.4 on 2023-09-09 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mikhalchuk', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='навзвание коллекции')),
                ('photo', models.ImageField(upload_to='')),
            ],
        ),
    ]
