# Generated by Django 4.2.7 on 2023-11-27 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mikhalchuk', '0003_collection_photo_delete_clothes_delete_collections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
