# Generated by Django 4.2.7 on 2023-12-03 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mikhalchuk', '0004_alter_collection_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('main_photo', models.ImageField(upload_to='collection_photos')),
            ],
        ),
        migrations.CreateModel(
            name='Jackets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('main_photo', models.ImageField(upload_to='collection_photos')),
            ],
        ),
        migrations.CreateModel(
            name='NewCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('main_photo', models.ImageField(upload_to='collection_photos')),
            ],
        ),
        migrations.CreateModel(
            name='ShirtsAndBlouses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('main_photo', models.ImageField(upload_to='collection_photos')),
            ],
        ),
        migrations.CreateModel(
            name='TrousersAndSkirts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('main_photo', models.ImageField(upload_to='collection_photos')),
            ],
        ),
        migrations.CreateModel(
            name='TrousersAndSkirtsPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='collection_photos')),
                ('TrousersAndSkirts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mikhalchuk.collection')),
            ],
        ),
        migrations.CreateModel(
            name='ShirtsAndBlousesPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='collection_photos')),
                ('ShirtsAndBlouses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mikhalchuk.collection')),
            ],
        ),
        migrations.CreateModel(
            name='NewCollectionPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='collection_photos')),
                ('NewCollection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mikhalchuk.collection')),
            ],
        ),
        migrations.CreateModel(
            name='JacketsPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='collection_photos')),
                ('Jackets', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mikhalchuk.collection')),
            ],
        ),
        migrations.CreateModel(
            name='DressPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='collection_photos')),
                ('Dress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mikhalchuk.collection')),
            ],
        ),
    ]
